name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta, nightly]
        exclude:
          # Reduce CI load by excluding some combinations
          - os: windows-latest
            rust: beta
          - os: macOS-latest
            rust: beta
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.rust }}-
          ${{ runner.os }}-cargo-

    - name: Check formatting
      if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
      run: cargo fmt --all -- --check

    - name: Run Clippy
      if: matrix.rust == 'stable'
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build
      run: cargo build --verbose --all-features

    - name: Build examples
      run: cargo build --examples --verbose --all-features

    - name: Run tests
      run: cargo test --verbose --all-features

    - name: Run tests with release mode
      run: cargo test --verbose --all-features --release

    - name: Run single-threaded tests
      run: cargo test --verbose --all-features -- --test-threads=1

    - name: Run Rayon example
      if: matrix.rust == 'stable'
      run: cargo run --example rayon --release

    - name: Run Rayon example with profiler
      if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
      run: cargo run --example rayon --features profiler --release

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-miri-${{ hashFiles('**/Cargo.lock') }}

  sanitizer:
    name: Address Sanitizer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-sanitizer-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests with AddressSanitizer
      run: |
        export RUSTFLAGS="-Z sanitizer=address"
        export RUSTDOCFLAGS="-Z sanitizer=address"
        cargo +nightly test --verbose --target x86_64-unknown-linux-gnu -Z build-std
      env:
        ASAN_OPTIONS: detect_odr_violation=0

  examples:
    name: Examples
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-examples-${{ hashFiles('**/Cargo.lock') }}

    - name: Build all examples
      run: cargo build --examples --all-features --release

    - name: Run Rayon example (basic)
      run: |
        echo "Running Rayon example without profiler..."
        timeout 300 cargo run --example rayon --release

    - name: Run Rayon example (with profiler)
      run: |
        echo "Running Rayon example with profiler..."
        timeout 300 cargo run --example rayon --features profiler --release

  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-bench-${{ hashFiles('**/Cargo.lock') }}

    - name: Run benchmarks
      run: |
        # Run the comprehensive end-to-end test as a benchmark
        cargo test test_end_to_end_write_read_cycle --release -- --nocapture --ignored
        
        # Run Rayon example as performance benchmark
        echo "Benchmarking Rayon example..."
        time cargo run --example rayon --features profiler --release
        
        # If you add criterion benchmarks later:
        # cargo bench --all-features

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    # Only run on main branch pushes
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-docs-${{ hashFiles('**/Cargo.lock') }}

    - name: Build documentation
      run: |
        cargo doc --all-features --no-deps --document-private-items
        # Create an index.html that redirects to your main crate docs
        echo '<meta http-equiv="refresh" content="0; url=synched_memory">' > target/doc/index.html

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./target/doc

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4